name: Build docs
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
    - name: Checkout submodules
      shell: bash
      run: |
        GIT_LFS_SKIP_SMUDGE=1 git submodule update --init -- references/akari_software
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |
        uv sync
    - name: Build documents
      run: |
        uv run make html
    - name: Deploy documents
      shell: bash
      if: github.ref == 'refs/heads/main'
      run: |
        tempdir=$(mktemp -d)

        cp -r _build/html $tempdir
        cd $tempdir/html
        touch .nojekyll

        git init
        git config user.name "Akari Group"
        git config user.email "akari.tmc@gmail.com"

        git checkout -B gh-pages
        git add .
        git commit -am "Build: $(date)"

        git remote add origin "https://git:${{ github.token }}@github.com/${{ github.repository }}"
        git push -f origin HEAD
